name: Angular CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'PMS.UI/**'
      - '.github/workflows/angular-ci.yml'

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: PMS.UI/package-lock.json

      - name: Install dependencies
        run: cd PMS.UI && npm ci

      - name: Run linter
        run: cd PMS.UI && npm run lint

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: PMS.UI/package-lock.json

      - name: Install dependencies
        run: cd PMS.UI && npm ci

      - name: Run tests
        run: cd PMS.UI && npm run test -- --watch=false --browsers=ChromeHeadless

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: PMS.UI/package-lock.json

      - name: Install dependencies
        run: cd PMS.UI && npm ci

      - name: Build Angular app
        run: cd PMS.UI && npm run build -- --configuration production