name: Angular CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'PMS.Ui/**'
      - '.github/workflows/angular-ci.yml'

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.0
          cache: 'npm'
          cache-dependency-path: PMS.Ui/package-lock.json

      - name: Install dependencies
        run: cd PMS.Ui && npm ci

      - name: Run linter
        run: cd PMS.Ui && npm run lint

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.0
          cache: 'npm'
          cache-dependency-path: PMS.Ui/package-lock.json

      - name: Install dependencies
        run: cd PMS.Ui && npm ci

      - name: Run tests
        

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.0
          cache: 'npm'
          cache-dependency-path: PMS.Ui/package-lock.json
      - run: cd PMS.Ui && npm ci
      - run: cd PMS.Ui && npm run build -- --configuration production
